# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lin Yang
email: lin.yang@utexas.edu
description: >
  Ruby on Rails, Javascript, Food Explorer, Productivity Passionist
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Lin Yang'
bio: >
  Junior Web Dev, little Techy & Geeky, love doing Kitchen Experiment, passion about 
  Time/ Task/ Knowledge Management. 
author_image: "/assets/images/squirrel.jpg"
github_username:  darktef

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
