# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lin Yang
email: lin.yang@utexas.edu
description: >
  Ruby on Rails/ Javascript/ Food Explorer/ Productivity Passionist
logo: "/assets/images/logo.png"

# Serving
baseurl: "" # the subpath of your site, e.g. /blog

# Site Owner Configure
name: 'Lin Yang'
bio: >
  Web Dev, little Techy & Geeky, love doing Kitchen Experiment, passion about 
  Time/ Task/ Knowledge Management. 
author_image: "/assets/images/squirrel.jpg"
social: 
  github: darktef
  instagram: darktef
  linkedin: linyang18

# Google Analytics
analytics_id: UA-79235858-1

# Conversion
markdown:    kramdown
highlighter: rouge
excerpt_separator: <!--more-->

# Outputting
timezone: America/Chicago
permalink: /posts/:year-:month-:title
paginate: 5 # The number of posts to show per page on your homepage
paginate_path: /page:num

# Markdown preprocessor
kramdown:
  parse_block_html: true

# Plugins
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-mentions
